# Generated by Django 3.2.25 on 2024-07-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('passport_photo', models.ImageField(upload_to='passports/')),
                ('nin_number', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=15)),
                ('registration_code', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
