# Generated by Django 3.2.25 on 2024-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
