# Generated by Django 3.2.25 on 2024-08-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('residents', '0002_auto_20240729_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='resident_set', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='resident_set', to='auth.Permission'),
        ),
    ]
